name: Build and Test Integration

on:
  push:
    branches: [ test/main ]
  pull_request:
    branches: [ test/main ]
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Deploy code?'
        required: true
        type: boolean
        default: false

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies via CI
        run: npm ci

      - name: Run unit testing via Jest
        run: npm run test

  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies via CI
        run: npm ci

      - name: Build application
        run: npm run build

  deploy-placeholder:
    runs-on: ubuntu-latest
    needs: [ test-app, build-app ]
    if: ${{ inputs.confirm_deployment }}

    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DEPLOY to production env
        run: echo 'Deploying code to production env.'